name: Output template

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      lambda_version: ${{ steps.set_lambda_version.outputs.lambda_version }}
    steps:
      - uses: actions/checkout@v3
      - name: CI
        id: ci
        uses: "./.github/workflows/template"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.lambda_version}}
        run: echo "$OUTPUT1"
            